################
## Background ##
################

ClipperData is a company who takes 

####################
## Analysis Needs ##
####################

No.1 航线追踪，整理出有问题的航线记录，结合数据可视化结果和航运公司发布的信息找出问题存在的原因，并以合适的方式将错误的信息改为正确的，
     最后将其更新到数据库中。航线追踪的目的是我们在建立货物需求量预测模型之前，需要保证我们所用到的数据是正确且符合真实情况的。
     
     谷物类：
     1. 先找到需要修改的记录
     select * from voyage_bulk_iss where lo_country_code = 'RU' and grade = 'ED033' AND SOURCE ILIKE '%MAKEUP%' and weight_mt > 10000
     union
     select * from voyage_bulk_iss where lo_country_code = 'UA' and grade = 'ED033' AND SOURCE ILIKE '%MAKEUP%' and weight_mt > 10000
     union
     select * from voyage_bulk_iss where lo_country_code = 'RU' and grade = 'ED037' AND SOURCE ILIKE '%MAKEUP%' and weight_mt > 10000
     union
     select * from voyage_bulk_iss where lo_country_code = 'UA' and grade = 'ED037' AND SOURCE ILIKE '%MAKEUP%' and weight_mt > 10000
     ORDER BY 14, 2 DESC
     
     2. 一条一条检查记录中特定时间点附近的船只航线draught变换记录，船只接卸地点，unload/load 记录是否正确
     SELECT * FROM asvt_arrival_dry
     where vessel =10159                                                                                                                                                               
     order by date_arrive DESC 
    
     3. 对错误信息进行修改
     Ⅰ 看航线记录的draught变换
       首先检查在指定日期附近draught变化是否连续，例如卸货为10-6紧接着下一个Load为6-10。如果中途有差错，一般为缺失了arrival导致记录混乱，或者draught
       记录出现错误。那么我们需要将正确的信息添加到指定的table里。
       
       缺失arrival   insert into asvt_arrival_x values(5770284, 2892, '2019-01-09 00:00:00') on conflict do nothing;
       draught错误   insert into asvt_draught_x values(6788, '2019-03-02 18:20:47',12.6) on conflict do nothing;
       
     Ⅱ 初步判断发现指定日期附近所有的draught没有错误
       这种情况往往需要我们更仔细去核对地图信息和我们的航线信息。有时候draught没有变化意味着错误的情况或许较为难发现。
       首先我们需要查看指定日期附近的这一段从load到unload的voyage是变化是否符合实际情况，再者是虽然draught看上去没有错误，但是连续好几个event都没有变化
       这 
 No.2  核对与agency report未匹配的航线信息。agency report的信息中会显示船只计划中到达港口的货物接卸情况，我们先找到与其未匹配的航线记录，然后
       进一步探索是航线记录出现问题，还是agency report的信息给错了。这两种情况都有可能发生。本质是我们需要让数据库识别到指定日期的记录被识别为
       U/L并且对应货种为指定货种。
  
       
        检查航线记录 
        首先通过bargo页面，找到船只的vessel id， 通过以下代码找到船只对应的航线记录 (原油对应——asvt_arrival，干货对应——asvt_arrival_dry）
        ```SQL
        SELECT * FROM asvt_arrival
        where vessel =1527333(vessel id)                                                                                                 
        order by date_arrive DESC 
        ```
        
       1. 航线记录在agency report指定的日期内卸货，此条记录没有U/L 标志和货种类别。按以下步骤层层确认信息。
       
          @1 draught明显有问题,更改draught 
             ```SQL
             insert into asvt_draught_x values(5364942, '2019-02-19 00:00:00', 14.8) on conflict do nothing;
             ```
          @2 查看是否缺失arrival，如若缺失，补上arrival (原油对应——asvt_arrival_x_values，干货对应——asvt_arrival_dry_x values）
             ```SQL
             insert into asvt_arrival_x values(15685, 101785, '2018-04-06 00:00:00') on conflict do nothing;
             ```
          @3 查看港口POI 是否可接卸指定货种，其港口名称是否与agency report中的地名统一 
             将bargo打开，查看接卸货物港口是否有POI指定货种接卸标志，如果没有，记录在待纠错的记录旁 (后续会介绍到POI类问题的解决方法）
             如果地名与agency report中的不同，我们需要查看两个地名是否是在同一个省份并且地理位置接近，如若是，我们强行匹配地名
             ```SQL
             insert into lookup.iss_vl_alias_port_group values('CN','TAO','CN','RZH') on conflict do nothing;
             insert into lookup.iss_vl_alias_port_group values('CN','RZH','CN','TAO') on conflict do nothing;
             ```
             如若地名在不同城市甚至不同国家，查看agency report前后几个月里是否有去过航线信息中港口的记录
             ```SQL
             select * from inchcape.iss_raw_archive_2 
             where vessel = 'GENER8 OCEANUS'
             order by operation_date DESC
             ```
             如果有，查看是否有相匹配的航线，匹配则删除待纠错记录，不匹配则强行force match the date
             ```SQL
             insert into inchcape.iss_process_mod values('KING DANIEL','ARRIVEDDATE','CRUDE OILS, TBC',0.00,'2018-09-19',
             'SHANGHAI',5744384,21256,'2018-09-27 05:49:11','2018-10-04 07:47:23');
             ```
             如果report中没有地图上的港口记录，那么将记录删除
             
          @4 查看agency report的船只类型
             如果report中该船大部分记录为clean的货种，但待纠错记录说接卸原油，那么我们可以确定agency report这条待纠错记录是错误的，我们将其删除
             ```SQL
             insert into asvt_arrival_x_out values(19425, 301882, '2018-11-23 11:58:17') on conflict do nothing;
             ```
          @6 修改agency report中的operation——direction
             当上述问题都被解决后，我们发现船只在指定日期，指定港口附近的货物进出口方向与report想法，我们此时根据地图实际看到的航线更改report中的
             operation——direction
             ```SQL
             insert into inchcape.iss_raw_archive_mod (operation, grade, quantity, vessel, port, operation_date, direction,grade_code)
             values('SAILEDDATE','MEREY 16',44764.00,'TIAN LONG ZUO','ZHUHAI','2018-01-25','Loading','') on conflict do nothing;
             ```
          @6 强行添加U/L 
             如果上述步骤都没有查找到问题，那么我们可以强行在指定航线记录中添加U/L 标志，以此让其匹配
             (这里有特殊公式）
          
       2. 航线记录不在agency report指定的日期内卸货，此条记录没有U/L 标志和货种类别。按以下步骤层层确认信息。
          
          @1 重复以上步骤查看航线实际信息是否正确
             
             确保draught变化符合实际情况，有错便更改
             确保没有missing arrival，有缺失便更改
             确保去了report给出的指定港口，没去就重复1@3的步骤
             确保船只是运输指定货种的船，不是就直接将agency report待纠错记录删除
             确保operation——direction 符合agency report的信息，不符合考虑更改方向
             确保agency report中没有与实际日期匹配的记录，如果有，就强行删除待纠错记录
             如果上述都确保正确后，强行force match 日期
              ```SQL
             insert into inchcape.iss_process_mod values('KING DANIEL','ARRIVEDDATE','CRUDE OILS, TBC',0.00,'2018-09-19',
             'SHANGHAI',5744384,21256,'2018-09-27 05:49:11','2018-10-04 07:47:23');
             ```
             
         3. 如果船只在指定港口没有draught变化，我们也找不到其他的错误信息，那么我们就强行删除待纠错agency report记录
         
    
    No.3 POI research
    
         当我们遇到No.2 1@3中，不确定指定POI是否可unload/load某种货物时，我们要做相应的港口调查，来确认信息
         
         1. 查找去过该POI且有对应的agent记录的信息有多少 (如果我们查找它是否可接卸原油，那么agent记录中也要是接卸原油的信息）
         ```SQL
         SELECT * FROM asvt_arrival
         WHERE vessel IN 
         (SELECT vessel FROM as_vessel_exp
         WHERE imo IN(
         select distinct imo from inchcape.iss_raw_archive_2 where port ilike '%jinshan%' 
         and grade ilike '%crude%' 
         ) 
         AND poi= 102743)
         order by 1,3 DESC
         ```
         
         2. 得到上述信息后，一条条查看相应船只的agent report中是否有匹配的货种接卸信息，得出船只去往该POI接卸某种货物的频数，作为补充信息
         ```SQL
         select * from inchcape.iss_raw_archive_2 
         where imo IN
         (select imo from as_vessel_exp
         where vessel =61613 ) and port ilike '%zhuhai%' and grade ilike '%crude%'
         order by operation_date DESC
         ```
         该步骤也看出该船只是否是可运输某种货物的船，如果不是，直接确定该POI不能接卸某货种。
         
         3. 搜索POI接卸码头，上网搜索相关码头货物接卸信息
         
         @1 搜索‘ 某某港口几号码头原油 规划与布置’ 有时能搜索到我们想要的信息
         @2 打开百度地图， 通过经纬度查找到该港口位置
         ```SQL
         select * from as_poi where poi =  102743
         ```
            查看管理该港口的公司的官网是否有介绍与码头相关的货物接卸报告
            例如搜索 ‘ Hong Kong International Airport Fuel Facility (PAFF)’ 
            
            查看百度地图上，POI附近是否有化工公司，搜索这些公司的官网是否有介绍与码头相关的货物接卸报告
            
          结合上述所有信息，进一步确认该POI是否可接卸某货种
            
          
 No.4 Operation_Date --- Data cleaning
      
       operation-date是指船只在某个时刻进行了货物接卸。日期的准确性也会影响用于预测未来某个时间段某个货种的货物量的模型的准确度。我们能拿到的数据，
       是各个agency发往我们邮件中的信息，很多信息参差不齐，没有统一的格式，并且数据也往往是错误的。所以我们首先核对了已知数据的格式，将数据同
       ‘0000-00-00’ 这种格式进行匹配，整理出匹配结果为FALSE的记录，对他们进行进一步的数据清洗。
       
       由于记录参差不齐，按理说我们应该每条待核对记录都应该与查看相关的文件来获取正确的日期，但有些日期只是格式需要改变，其日期本身是正确的，
       那么我们可以通过正则化匹配来对数据进行。
       
       @1 这里我们会运用到PostgreSQL 的正则化规则。
       @2 当遇到不可以用正则化做信息匹配的时候，我们可以target出现次数较多的文件，用VBA抓取相关信息，导入PostgreSQL中，形成临时的表格，用正则提取
       正确的日期，然后将数据在EXCEL中进行更正。
       @3 有时候用excel套公式会更方便，例如我们要replace某个columns的时候，用excel会更方便
       
       我工作中的缺点：不会灵活运动过去的工作经验，比较按部就班，理解能力较差，需要不断学习的东西还有很多，要勇于请教问题。
       *** 拿到数据后，首先观察数据，数据可否直观地进行分类（1.时间正确，格式不正确，可正则化匹配进行批量处理；2. 其他的形式，可以order source_file
       ,查看同一个文件内的东西是否可以把日期摘出来并转移到EXCEL中，拉公式，提高处理效率。）
       *** 当面对要从PDF或者EXCEL中提取大量的数据的时候，我们可以通过VBA将筛选出的数据转移到数据库中，用SQL对数据进行筛选操作，生成新的结果后，又
       将结果返还到EXCEL中
       *** 拿到port数据后，order source file，找出来自同一个文件的记录，先检查记录中port是否有拼写错误，如果没有则看文件中是否有port的正确信息，
       如果没有，我们就需要利用vessel名字，找到bargo中的信息，对港口记录进行纠正。最后的结果同样可以用EXCEL拖拉公式的方法进行处理。会高效很多。
       
       做工作一定要认真反反复复地检查，在上交工作前，一定要反反复复检查。注意质量，注意格式。
       
       @在反复实践中学到的小技巧：1. 先通过正则处理不需要文件信息的记录(正则技能get) 2. 将记录按文档(source_file)排序，在excel中通过公式进行拖拉，
       更加方便直接。但要注意不要跳行。3. 运用到正则的时候记得记录下row 行数，这样以防不注意insert了很多不相关的行数。
       ```SQL
        select * from alert.inchcape_iss_raw_archive_discard
        where x_out = 'f' 
        and rec_operation_date = 'f' and operation_date != '' 
        and operation_date ~* 'A/SIDE'
        order by source_file limit 53;
        ```
        ```SQL
        insert into inchcape_prod.iss_raw_archive_mod_pkey
        (operation, grade_raw, quantity, vessel, port, operation_date, operation_date_new)
         select operation, grade, quantity, vessel, port, operation_date, 
        concat(substring(report_date,7,4),'-','0',substring(operation_date,4,2),'-',substring(operation_date,1,2))
         from alert.inchcape_iss_raw_archive_discard
         where x_out = 'f' 
         and rec_operation_date = 'f' and operation_date != '' 
         and operation_date ~* '^(\d{2})\/(\d{2})  (\d{2})\:(\d{2})';
         ```
         记住在EXCEL里，当复制粘贴代码的时候会出现引号“ ”是因为代码没有在一行~ 这个时候要用 CLEAN()公式清楚格式。并且在代码里面，某些关键词记得要留
         空格，不然clean后这些关键词可能会和上一个词连接在一起，导致关键词失效。
         
         
         ***@@**** 最近找到了一种除了用正则匹配，更为高效的方式来处理数据
            1. 首先我们通过找到出现错误信息的所有的source_file,根据出现的次数对其进行排序，从出现次数最多的文件开始批量处理。
            ```SQL
             select source_file, source_sheet, count(*) from alert.inchcape_iss_raw_archive_discard
             where x_out = 'f' 
             and rec_operation_date = 'f' and operation_date != '' 
             group by source_file,source_sheet order by count(*) DESC
             ```
            2.其次我们依次从clipper_data 谷歌account中找到这些文件，通过VBA Macro宏的方法，将文件中的船只，ETA等信息抓取出来，具体代码如下：
            ```
            Sub Macro3()
               Columns("A:O").Select
               With Selection
               .WrapText = False
               .Orientation = 0
               .AddIndent = False
                .IndentLevel = 0
               .ShrinkToFit = False
               .ReadingOrder = xlContext
                .MergeCells = False
            End With
               Selection.Replace What:="'", Replacement:="`", LookAt:=xlPart, SearchOrder _
                :=xlByRows, MatchCase:=False, SearchFormat:=False, ReplaceFormat:=False
               Columns("A:A").Select
               Selection.Insert Shift:=xlToRight, CopyOrigin:=xlFormatFromLeftOrAbove
               Range("A1").Select
               ActiveCell.FormulaR1C1 = _
                     "=CONCAT(""('"",TEXTJOIN(""','"",FALSE,RC[1]:RC[14]),""'),"")" 
               Selection.AutoFill Destination:=Range("A1:A2000"), Type:=xlFillDefault
               Range("A1:A2000").Select
               Selection.Copy
            End Sub
            ```
            ActiveCell.FormulaR1C1 = _
                     "=CONCAT(""('"",TEXTJOIN(""','"",FALSE,RC[1]:RC[14]),""'),"")" 
            这一部分可以自由更改，常用的公式是， ="('"&B11&"','"&TEXT(D11,"yyyy-mm-dd")&"'),"
            
            3. 抓取到所需信息后，我们需要将这些信息粘贴到PostgreSQL里面，将这个写信insert新的表中，这样方面我们在SQL中批量筛选和处理数据。
            ```SQL
            drop table if exists p1;
            CREATE temporary TABLE P1 (
               c1 TEXT,
               c2 TEXT
            );
               INSERT INTO P1 VALUES
            ---------------------------------
               ('AU ARIES','2015-08-29'),
               ('HELEN 118','2015-08-31'),
            --------------------------------
               ('','')
               ;
           ```
           
           4. 对数据进行批量筛选和处理
           ```SQL
           SELECT operation, grade, quantity, vessel, port, operation_date,c2 --and substring(c2,1,2) NOT IN ('11','12','13','14','15') 
           ,CASE WHEN substring(c2,1,1) IN ('1','2','3') and substring(c2,1,2) not IN ('11','12','13','14','15','16')  
           THEN concat(substring(report_date,7,4),'-','08','-',substring(c2,1,2))
           ELSE concat(substring(report_date,7,4),'-','09','-',substring(c2,1,2)) END as time
          FROM
          (select *,row_number() over(partition by vessel,quantity,operation,grade order by c2) rank
          FROM
          (select *
          from alert.inchcape_iss_raw_archive_discard
          where x_out = 'f' 
          and rec_operation_date = 'f' and operation_date != '' 
          and source_file ~* 'APAC 37 - 1 2016__09-16-2016__.xlsm'
          )a
          INNER JOIN
          (
          select substring(c1,5,20) vs,c2 from p1  
          )b
          ON a.vessel=b.vs
          )c
          where rank = 1 --and c2 !~* '^(\d{2})\/(\d{2})' 
          --and c2 !~* '^(\d{2})\/' and c2 ~ '^(\d{4})'
          ```

No. 5  Advanced SQL usage

@1 TIME PROBLEM - Calculation / Extract 
```SQL
SELECT date_trunc('year', now() - interval '5 year') -- extract part of the date to do calculation
SELECT now() - '3 year'::interval -- to do calculation as timestampe
SELECT (now() - '3 year'::interval)::date -- to do do calculation as timestamp but convert it to date format
SELECT extract('year' from current_date) -- extract part of the date
```

@2 GENERATE RANDOM VALUES
```SQL
select (random()*10)::int as num, count(*)
from generate_series(1,200)-- generate n values 
group by num
```

@3 MAKE VALUE INTO INTEGER
```SQL
SELECT floor(random()*(25-1+1))+1 -- convert into integer (24.12/24.57 -> 24)
SELECT ceiling(random()*(25-1+1))+1 -- convert into integer (24.12/24.57 -> 25)
SELECT round(random()*(25-1+1))+1 -- convert into integer (24.12/24.57 -> 24/25)
```

@ CREATE TABLE / INSERT DATA/ USING 'LATERAL'
```SQL
--- Create a temporary table
DROP TABLE IF EXISTS test;
CREATE TEMP TABLE test(
username TEXT,
user_id INT,
region TEXT,
salary INT);
```

```SQL
--- Insert data into the table
INSERT INTO test (username,user_id,region,salary)
SELECT 'host # ' || (random()*(10-1)+1)::int,  -- use '||' to connet things(but have to have strings)
       (random()*(2000-1000)+1000)::int, -- generate random numbers with a specific range FROM 1000 to 2000
       'US - ' || (random()*(20-1)+1)::int, 
       (random()*(20000-2000)+2000)::int
FROM (SELECT * 
      FROM generate_series(1,100))a;
```

```SQL 
--- Using 'LATERAL' to select the information 
SELECT two.* FROM
(       
SELECT * FROM(
SELECT username, salary, region, rank() over(partition by region order by salary) rank
FROM test t1)a WHERE a.rank IN(4,6)
) AS one
, 
LATERAL(SELECT * FROM(  --- 'LATERAL' can let the subquery use condition from another parrellel table
SELECT username, salary, region, rank() over(partition by region order by salary) rank
FROM test t2)b WHERE b.rank IN (2,3) and one.region = b.region) AS two
```

### Decimal
```SQL
select round((73600 - 12000)/(98000-12000)::numeric,4) --- 0.716
```





     
    
       
       
         
          
       
          
     
      


     
 
