##############################
#### SQL coding practice #####
##############################

## Q1 : Find out the students choosing Course1 has greater grade than the ones who choose Course2.

Tip: Find out the students choosing Course1 or Course2 first;
     Using join with the main table with 'where' to filter the result on 'greater grade' condition;
     < We can compare the grade during the 'join' process >
```SQL
SELECT a.s_num, a.stu_name
FROM
(SELECT s_num,stu_name 
FROM Student)a

INNER JOIN
(SELECT s_num,grade 
FROM Course
WHERE course=1)b
ON a.s_num=b.s_num

INNER JOIN
(SELECT s_num,grade 
FROM Course
WHERE course=2)c
ON b.s_num=c.s_num

WHERE b.grade>c.grade
```
Tip : We need to find out cd_name having both A and B comodity;
      We use 'Join' to join them so they can be rows with same cd_name and compared with each other
      Use the 'Where' filter outside these two subqueries
```SQL
SELECT a.cd_name,a.poi,b.poi
FROM
(SELECT cd_name, poi FROM as_poi 
		where lo_country_code= 'CN' 
		and lo_city_code ='NJG'
		and cmdty='CDFG')a 
INNER JOIN (SELECT cd_name, poi FROM as_poi 
		where lo_country_code= 'CN' 
		and lo_city_code ='NJG'
		and cmdty='CDFG')b ON a.cd_name=b.cd_name
WHERE a.poi > b.poi
```

### Q2 : Find out the anchors who are level 2 but have higher socre than the ones with level 1

Tip : We just need to find out the anchors whose scores are larger than the minimum socre of level 1 anchors;
      So here we can use 'where' clause, because we can set score < specific number.
```SQL
SELECT cd_name, poi FROM as_poi 
		where lo_country_code= 'CN' 
		and lo_city_code ='NJG'
		and cmdty='CDFG'
		and poi < (select min(poi) FROM as_poi 
		where lo_country_code= 'CN' 
		and lo_city_code ='NJG'
		and cmdty='K') 
```

## Q3 : Find out the students who have average score larger than 60

Tip : Find out the student_id whose avg scores are larger than 60 first;
      Then using 'INNER JOIN' to get the student_name from S table.

```SQL
select s.s_name,s.s_no,c.avg(grade)
from S s
inner join
(select s_no,avg(grade) from C c group by s_no having avg(grade) > 60 ) ON s.s_no=c.s_no
```

## Q4 : Find out the students who failed all the courses

Tip : Find out the student_id who has at least one course with 60 or more
      Then using 'NOT IN' in that range to get the student_name from S table.

```SQL
SELECT stu_name
FROM student
WHERE stu_num NOT IN ( SELECT stu_num FROM course where grade > 60)
```

## Q5 ： Find out the sum of the quantity where operation = 'BLADE‘

Tip : Notice that there would be an aggregation function 'sum()';
      Use 'group by' at the end; 
```SQL
select operation, sum(quantity)
from inchcape.iss_raw_archive_2 
where vessel = 'ASTOMOS VENUS'
and operation = 'BLDATE'
group by operation
```

# Q6 ： Find out the students who take all same courses with student 1

Tip: Find out the courses student1 take first;
     Then find out students who take at least one course different from student1;
     select out the students whose id are different from second step;
```SQL     
SELECT stu_id FROM COURSE WHERE stu_id NOT IN
(SELECT stu_id FROM COURSE WHERE c_id NOT IN
(SELECT c_id FROM Course WHERE stu_id = 1))
GROUP BY stu_id
HAVING count(*) = 
(SELECT count(c_id) FROM COURSE
WHERE stu_id = 1) and stu_id =!1
```

## Q7 : Find out the student and their avg_grade who have failed more than tow course 

Tips : Find out the students who failed more than two courses;(using GROUP BY and AVG)
       INNER JOIN the table 
```SQL
SELECT a.stu_name, b.avg_sc FROM
(SELECT stu_id, stu_name FROM Student)a
INNER JOIN 
(
SELECT stu_id,avg(grade) as avg_sc FROM Course
WHERE grade < 60
Group by stu_id
HAVING count(c_id) >2 
)b
ON a.stu_id = b.stu_id
```
## Q8 : Find out the pass_rate...

Tips : Find out how to calcualte the pass_rate; (using AVG(0,1) to calculate this)
```SQL
SELECT c_id, c_name, MAX(grade),Min(grade),AVG(grade),
       AVG(CASE WHEN grade >= 60 THEN 1 ELSE 0 END),
       AVG(CASE WHEN grade >= 70 AND grade <= 80 THEN 1 ELSE 0 END),
       AVG(CASE WHEN grade >= 80 AND grade <= 90 THEN 1 ELSE 0 END),
       AVG(CASE WHEN grade >= 90 THEN 1 ELSE 0 END)
FROM Course
GROUP BY c_id,c_name
```

## Q9 : Find out the score rank of every course

Tips : Find out the score rank of every course;(using ROW_NUMBER() OVER(PARTITION BY course ORDER BY grade)

```SQL
SELECT created_by,cmdty, poi, 
row_number() over(partition by cmdty order by poi DESC) rank FROM as_poi
where cmdty IN ('C','R') and created_by IN ('austin_swertfager','yuwen_li','demi_alifu')
order by cmdty,poi DESC
```

## Q10 : Find out the score rank of 2 and 3 in every course

Tips : Find out the score rank of every course;(using ROW_NUMBER() OVER(PARTITION BY course ORDER BY grade)

```SQL
select stu_id,c_id, grade, row_number(partition by c_id order by grade DESC) rank
from course
where rank IN (2,3)
```

## Q11 : Find out the number of each level in every course

Tips : Find out the the number of every level;
       (using count(case when then 1 else null);
```SQL
select c_id, 
       count(case when grade < 60 then 1 else null) pass_rate,
       count(case when grade > 70 and grade <80 then 1 else null) med_rate,
       count(case when grade < 80 and grade <90 then 1 else null) good_rate,
       count(case when grade > 90 then 1 else null) exc_rate
from course
group by c_id
```

## Q12 : Find out the students who were born in 1990

```SQL
select stu_id,stu_name
from student
where year(birth) = 1990
```
```SQL
select stu_id,stu_name
from student
where birth like '%1990'
```


## Q13 : Find out the students who have more than courses with same grade

```SQL
select stu_id,c_id,grade from course c1
inner join
select stu_id, c_id, grade from course c2
on c1.stu_id=c2.stu
where c1.c_id != c2.c_id and c1.grade = c2.grade
```
https://blog.csdn.net/a379850992/article/details/55655495


## Q14 : Delte the records that has same information with original one
```SQL
DELETE * WHERE id NOT IN ( SELECT MIN(id) FROM table GROUP BY name,course,socre)
```

## Q15 : There is a table with one column " name", find the groups of two-two play 
```SQL
SELECT a.team, b.team FROM team a, team b WHERE a.team < b.team
```

## Q16 : Find out the id that has larger money than '101' in every month

```SQL
SELECT *, (SELECT month, max(money) FROM table WHERE id=101 GROUP BY month)b
FROM table a
WHERE a.month = b.month and a.money > b.max(money)
```

## Q17 copy the table

SQL: select * into b from a where 1<>1       (where1=1，拷贝表结构和数据内容)
Oracle:create table b

As

Select * from a where 1=2

[<>（不等于）(SQL Server Compact)
比较两个表达式。 当使用此运算符比较非空表达式时，如果左操作数不等于右操作数，则结果为 TRUE。 否则，结果为 FALSE。]

## Q18 : Remind of something ahead of 5 mins
```SQL
SELECT event FROM table WHERE datediff('minute',f 开始时间,getdate())>5 
```
## Q19 : 两张表，一张含有员工ID和薪水情况，另一张含有部门ID和员工ID，提取出每个部门薪水最高的员工及其薪水
【考点：两种方法。1.使用窗口函数，先将两张表连接为一张表，拉通了进行部门分组排序，这样你就可以看到每一组的第一名是谁，最后选出第一名的员工即可
               2.使用group by 与max()。将两张表连接，先提取出每个部门最高薪水的小表，然后将小表与大表内连接
```SQL
SELECT dept_no
       ,emp_no
       ,salary AS maxSalary
FROM (
        SELECT dept_no
               ,s.emp_no
               ,salary
               ,RANK() OVER (PARTITION BY dept_no
                           ORDER BY salary DESC) AS ranking
        FROM dept_emp d
        JOIN salaries s
        ON d.emp_no=s.emp_no
        WHERE d.to_date='9999-01-01'
              AND s.to_date='9999-01-01'
      )a
WHERE a.ranking=1;
```
```SQL
SELECT d.dept_no
        ,s.emp_no
        ,s.salary
FROM dept_emp d
JOIN salaries s
ON d.emp_no=s.emp_no
   AND d.to_date='9999-01-01' AND s.to_date='9999-01-01'
JOIN 
(SELECT dept_no
         ,MAX(salary) AS maxSalary
 FROM dept_emp d
 JOIN salaries s
 ON d.emp_no=s.emp_no
 WHERE d.to_date='9999-01-01' AND s.to_date='9999-01-01'
 GROUP BY dept_no)a
 ON d.dept_no=a.dept_no
    AND s.salary=a.maxSalary;
```
## Q20 : 一张含有职位和薪水情况的表，提取出每个部门平均薪水
【考点：group by avg()之后的结果，可以在order BY里直接用】
```sql
SELECT t.title
       ,avg(salary) as avg_salary
FROM titles t
JOIN salaries s
ON t.emp_no=s.emp_no 
   AND t.to_date='9999-01-01'
   AND s.to_date='9999-01-01'
GROUP BY title
ORDER BY avg_salary;
```
## Q21 : 一张表含有员工信息，一张表含有薪水信息，找到当前薪水第二高的员工的信息，不能用order by
【考点：难点在于如何找到第二高的员工，我们将同一张表进行连接，连接条件是表1每一行连接行另一张表比每一行大的所有数，这样第一大的就没有，第二大连接第一大的，以此类推】
```sql
SELECT a.emp_no
        ,a.salary
        ,last_name
        ,first_name
FROM
(SELECT s1.emp_no
        ,s1.salary
        ,count(DISTINCT s2.salary) AS ct
FROM salaries s1
INNER JOIN salaries s2
ON s1.salary < s2.salary
WHERE s1.to_date='9999-01-01'
      AND s2.to_date='9999-01-01'
GROUP BY s1.salary
)a
JOIN employees e
ON e.emp_no=a.emp_no
WHERE a.ct=1;
```
## Q22 : 一张表含有员工信息，将员工的姓名连接起来
【考点：考察 concat公式，concat（a,",",b)】
## Q23 : 插入数据
【考点：insert in table (column1, col2,...)
       values
       (1,2,2..),
       (1,2,2..);】
【考点：如果表里已经有这个数据了，不操作。
mysql中常用的三种插入数据的语句:
insert into表示插入数据，数据库会检查主键，如果出现重复会报错；
replace into表示插入替换数据，需求表中有PrimaryKey，或者unique索引，如果数据库已经存在数据，则用新数据替换，如果没有数据效果则和insert into一样；
`insert ignore`表示，如果中已经存在相同的记录，则忽略当前新数据；
insert ignore into actor values("3","ED","CHASE","2006-02-15 12:34:33");
## Q24:
本题目考察MYSQL创建数据表的三种方法：
常规创建
1.create table if not exists 目标表
复制表格
2.create 目标表 like 来源表
3.将table1的部分拿来创建table2 （create 表 然后insert into 这个表 直接select想要内容）

MySQL中四种方式给字段添加索引
发表于 2020-11-18 13:14:04
看大家都用的是sqlite的语法，这里简单提一下关于MySQL中给字段创建索引的四种方式：

添加主键
ALTER TABLE tbl_name ADD PRIMARY KEY (col_list);
// 该语句添加一个主键，这意味着索引值必须是唯一的，且不能为NULL。
添加唯一索引
ALTER TABLE tbl_name ADD UNIQUE index_name (col_list);
// 这条语句创建索引的值必须是唯一的。
添加普通索引
ALTER TABLE tbl_name ADD INDEX index_name (col_list);
// 添加普通索引，索引值可出现多次。
添加全文索引
ALTER TABLE tbl_name ADD FULLTEXT index_name (col_list);
// 该语句指定了索引为 FULLTEXT ，用于全文索引。
PS: 附赠删除索引的语法：
DROP INDEX index_name ON tbl_name;
// 或者
ALTER TABLE tbl_name DROP INDEX index_name；
ALTER TABLE tbl_name DROP PRIMARY KEY;
SELECT * FROM salaries FORCE INDEX(idx_emp_no) WHERE emp_no = 10005; `强制索引`

## Q25  创建视图～
CREATE VIEW v_article AS SELECT A.title, A.content, A.author, C.name AS categoryName FROM article AS A JOIN articleCategory AS C ON A.articleCategoryId=C.articleCategoryId;

## Q26 新增一列
alter table actor 
add `create_date` datetime not null default '2020-10-01 00:00:00';

## Q27 创建触发器
触发器的作用是监视某个动作并对此做出反应。例如可创建一个触发器为：当在一张表中插入新的数据后，相应地就要在另一个表里加入相应地数据。
 ```sql
 create trigger audit_trigger
 after 
 insert on table1
 for each row
 begin
insert into table2 values (a.id,a.name);
 end
 ```
 ## Q28 从表里删除东西,以及更新表的内容
```sql
 delete from titles_test
where id not in(
    select * 
        from (
              select min(id)
                  from titles_test
                    group by emp_no
        )a
);
UPDATE 表名称 SET 列名称 = 新值 WHERE 列名称 = 某值
```

## Q29 将已有的表中的值替换成新的数,更新表名,创建外键
```sql
update table1 set column1=
replace(column1,value_old,value_new)
where ....;

ALTER TABLE titles_test RENAME TO titles_2017

创建外键 ALTER TABLE audit ADD CONSTRAINT FOREIGN KEY (emp_no) REFERENCES employees_test(id);
```
## Q30 更新表中的信息
```sql
update salaries
set salary=salary*1.1
where to_date="9999-01-01" and emp_no in
(
    select emp_no
    from emp_bonus
);
```
## Q31 替换字符串 replace(字符串，“需要替换的子串”，“用于替换子串的字符串”）
## Q32 排除某列中的最大最小值，不可以同时选择最大最小值，在一个括号中，因为每次选择都是一列，这样就成了两列了，而不是一个集合
